"""Default configuration for the 9x9 Go reinforcement learning demo."""

from pathlib import Path


PACKAGE_DIR = Path(__file__).resolve().parent
DATA_DIR = PACKAGE_DIR / "data"
CHECKPOINT_DIR = PACKAGE_DIR / "checkpoints"
RESULTS_DIR = PACKAGE_DIR / "results"

BOARD_SIZE = 9
KOMI = 7.5
ACTION_SIZE = BOARD_SIZE * BOARD_SIZE + 1
PASS_ACTION = BOARD_SIZE * BOARD_SIZE

DEFAULT_SIMULATIONS = 100
DEFAULT_C_PUCT = 1.5
DEFAULT_MAX_MOVES = 200
DEFAULT_TEMPERATURE_MOVES = 20

DEFAULT_GAMES = 20
DEFAULT_EPOCHS = 5
DEFAULT_BATCH_SIZE = 64
DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_WEIGHT_DECAY = 1e-4

LATEST_DATA_PATH = DATA_DIR / "self_play_latest.npz"
LATEST_CHECKPOINT_PATH = CHECKPOINT_DIR / "latest.pt"
